# Generated by Django 3.2.6 on 2021-08-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
